# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='type',
            field=models.ForeignKey(db_column='noteType', on_delete=django.db.models.deletion.CASCADE, to='notes.NotesType'),
        ),
    ]
